height = int (input("What is your height in inches?"))
weight = int(input("What is your weight in lbs?"))
hsquared = (height**2)
hdivw = (weight/hsquared)
bmi = (703 * hdivw)
print("Your bmi is", bmi)
