print("         * ")
print("        ***")
print("        X*X")
print("       XXXXX")
print("      XXXXXXX")
print("     XX*XXXXXX")
print("      XXXXXXX")
print("     XXXXXX*XX")
print("    XXXXXXXXXXX")
print("   XXX*XXXXXXXXX")
print("    XXXXXXXXXXX")
print("   XXXXXXXXX*XXX")
print("  XXXXXXXXXXXXXXX")
print(" XXXXXXXXX*XXXXXXX")
print("   XXXXXXXXXXXXX")
print("  XXXXX*XXXXXXXXX")
print(" XXXXXXXX*XXXXXXXX")
print("XXXXXXXXXXXXXXXXXXX")
print("       ######")

